# Generated by Django 3.0.4 on 2020-03-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200321_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyable',
            name='buyable_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='buyable',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=1000),
        ),
    ]
