# Generated by Django 3.0.4 on 2020-03-19 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20200319_2109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='buyable',
            new_name='buyables',
        ),
    ]
