# Generated by Django 3.0.4 on 2020-03-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20200321_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyable',
            name='buyable_name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='buyable',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True),
        ),
    ]
