# Generated by Django 3.0.4 on 2020-03-23 19:08

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(null=True)),
                ('createdDateTime', models.DateTimeField(auto_now_add=True)),
                ('changedDateTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strasse', models.CharField(max_length=120, null=True)),
                ('hnummer', models.CharField(max_length=120, null=True)),
                ('plz', models.PositiveIntegerField(null=True)),
                ('ort', models.CharField(max_length=120, null=True)),
                ('state', models.CharField(default=None, max_length=40, null=True)),
                ('country', models.CharField(default='Deutschland', max_length=40, null=True)),
            ],
            options={
                'verbose_name': 'User Address',
                'verbose_name_plural': 'User Address',
            },
        ),
        migrations.CreateModel(
            name='Organiser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('organisation_name', models.CharField(max_length=120)),
                ('organisation_type', models.CharField(max_length=120)),
                ('contact_first_name', models.CharField(max_length=120)),
                ('contact_last_name', models.CharField(max_length=120)),
                ('contact_phone', models.CharField(max_length=100, null=True)),
                ('iban', models.CharField(max_length=120, null=True)),
                ('bic', models.CharField(max_length=120, null=True)),
                ('bank_account_owner', models.CharField(max_length=120, null=True)),
                ('kontosite', models.CharField(blank=True, max_length=120, null=True)),
                ('user_address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_adress_contact_set', related_query_name='organiser_address', to='accounts.UserAddress')),
            ],
            options={
                'verbose_name': 'Organiser',
                'verbose_name_plural': 'Organiser',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
