# Generated by Django 3.0.4 on 2020-03-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=120)),
                ('repeat_password', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Organiser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(max_length=120)),
                ('first_name_contact', models.CharField(max_length=120)),
                ('last_name_contact', models.CharField(max_length=120)),
                ('phone_contact', models.CharField(max_length=120)),
                ('iban', models.CharField(max_length=120)),
                ('bic', models.CharField(max_length=120)),
                ('bank_account_owner', models.CharField(max_length=120)),
                ('website', models.CharField(max_length=120)),
                ('shop', models.CharField(max_length=120)),
            ],
        ),
    ]
