# Generated by Django 3.0.4 on 2020-03-20 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.AddField(
            model_name='organiser',
            name='mail',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='organiser',
            name='password',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='organiser',
            name='repeat_password',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
