# Generated by Django 3.0.4 on 2020-03-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organiser',
            name='contact_phone',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
