# Generated by Django 3.0.4 on 2020-03-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.TextField()),
                ('pwd', models.TextField()),
                ('pwd_repeat', models.TextField()),
            ],
        ),
    ]
