# Generated by Django 3.0.4 on 2020-03-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mail',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='pwd',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='pwd_repeat',
            field=models.CharField(max_length=200),
        ),
    ]
